import mongoose, { Document, Model } from 'mongoose';

export interface ITicketFile {
  name: string;
  type?: string;
  preview?: string;
}

export interface ITicketReply {
  message: string;
  date: Date;
  author: string;
}

export interface ITicket extends Document {
  ticketId: string;
  subject: string;
  category: string;
  description: string;
  userName: string;
  userEmail: string;
  user?: mongoose.Types.ObjectId;
  status: 'Open' | 'Replied' | 'Closed';
  files: ITicketFile[];
  replies: ITicketReply[];
  createdAt: Date;
  updatedAt: Date;
}

const TicketFileSchema = new mongoose.Schema<ITicketFile>({
  name: { type: String, required: true },
  type: { type: String },
  preview: { type: String }
});

const TicketReplySchema = new mongoose.Schema<ITicketReply>({
  message: { type: String, required: true },
  date: { type: Date, required: true, default: Date.now },
  author: { type: String, required: true }
});

const TicketSchema = new mongoose.Schema<ITicket>(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
      ticketId: {
        type: String,
        required: true,
        unique: true,
        default: () => `TKT-${Math.random().toString(36).slice(2, 9).toUpperCase()}`
      },
    subject: { type: String, required: true },
    category: { type: String, required: true },
    description: { type: String, required: true },
    userName: { type: String },
    userEmail: { type: String },
    status: { type: String, required: true, default: 'Open' },
    files: { type: [TicketFileSchema], default: [] },
    replies: { type: [TicketReplySchema], default: [] }
  },
  { timestamps: true }
);

// ticketId is generated by the field default so it's available during validation

const Ticket: Model<ITicket> = mongoose.model<ITicket>('Ticket', TicketSchema);

export default Ticket;
